//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Ext2Mgr.rc
//
#define MANIFEST_RESOURCE_ID            1
#define ID_RELOAD_DL                    3
#define IDM_ABOUTBOX                    0x0010
#ifndef RT_MANIFEST
#define RT_MANIFEST                     24
#endif
#define IDM_CLOSE_SPLASH                0x0020
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_EXT2MGR_DIALOG              102
#define ID_INDICATOR_MESSAGE            103
#define ID_INDICATOR_TIME               104
#define ID_INDICATOR_EXTRA              105
#define IDR_MAINFRAME                   128
#define IDR_TRAY                        133
#define IDI_FLOPPY                      134
#define IDI_CDROM                       135
#define IDI_DISK                        136
#define IDI_DVD                         137
#define IDI_DYNAMIC                     138
#define IDR_MENU                        139
#define IDB_ABOUT_SCREEN                151
#define IDR_STANDARDBAR                 162
#define IDB_ABOUT_SMALL                 163
#define IDI_BIG_MAINFRAME               164
#define IDB_LINE_SEP                    166
#define IDD_SERVICE_MANAGE              167
#define IDD_FORMAT                      169
#define IDD_EXT2_ATTR                   170
#define IDD_CHANGE_MOUNTPINT            171
#define IDD_NEW_MOUNTPOINT              172
#define IDD_PROPERTY_DIALOG             173
#define IDD_DONATE_DIALOG               174
#define IDB_SMALL_PENGUIN               184
#define IDB_BIG_PENGUIN                 185
#define IDD_PERFSTAT_DIALOG             186
#define IDD_PARTITION_TYPE              187
#define IDD_REMOVE_DEADLETTER           188
#define IDR_AKEY_EXT2MGR                190
#define IDR_RCDAT_SRV                   191
#define IDC_VOLUME_LIST                 1001
#define IDC_AUTHOR                      1002
#define IDC_ABOUT_SHOW                  1003
#define IDC_PROGRAM                     1004
#define IDC_EXT2FSD                     1005
#define IDC_DISK_VIEW                   1006
#define IDC_DISK_LIST                   1007
#define IDC_READ_ONLY                   1013
#define IDC_EXT3_WRITABLE               1014
#define IDC_COMBO_STARTUP               1015
#define IDC_COMBO_CODEPAGE              1016
#define IDC_COMBO_DRVLETTER             1017
#define IDC_COMBO_AUTOMP                1018
#define IDC_EXT3_AUTOMOUNT              1018
#define IDC_FORMAT_PROGRESS             1019
#define IDC_COMBO_FS                    1020
#define IDC_FORMAT_TITLE                1021
#define IDC_EDIT_LABEL                  1022
#define IDC_COMBO_CLUSTER               1023
#define IDC_QUICK_FORMAT                1024
#define IDC_QUICK_COMPRESS              1025
#define IDC_DRV_LETTER_LIST             1026
#define IDC_DRVLETTERS_LIST             1028
#define IDC_PROPERTY_DEVICE             1029
#define IDC_PROPERTY_SDEV               1030
#define IDC_VENDOR_ID                   1031
#define IDC_PRODUCT_ID                  1032
#define IDC_SERIAL_NUMBER               1033
#define IDC_BUS_TYPE                    1034
#define IDC_DEVICE_TYPE                 1035
#define IDC_MEDIA_TYPE                  1036
#define IDC_TOTAL_SIZE                  1037
#define IDC_SDEV_CHANGE_MP              1038
#define IDC_MOUNT_POINTS                1039
#define IDC_VIA_SOURCEFORGE             1040
#define IDC_SDEV_SIZE                   1041
#define IDC_VIA_PAYPAL                  1042
#define IDC_FILE_SYSTEM                 1043
#define IDC_VIA_TAOBAO                  1043
#define IDC_SDEV_STATUS                 1044
#define IDC_DECLARE                     1045
#define IDC_SERVICE_STATUS              1046
#define IDC_SDEV_EXT2_INFO              1047
#define IDC_GLOBAL_PREFIX               1047
#define IDC_SDEV_FREE_SIZE              1048
#define IDC_GLOBAL_SUFFIX               1048
#define IDC_START_SERVICE               1049
#define IDC_PERMANENT_MP                1050
#define IDC_DOSDEV_MP                   1051
#define IDC_REGISTRY_MP                 1052
#define IDC_EXT2_PREFIX                 1053
#define IDC_EXT2_SUFFIX                 1054
#define IDC_PERFSTAT_INTERVAL           1055
#define IDC_MEMORY_LIST                 1056
#define IDC_IRP_LIST                    1057
#define IDC_AUTOMOUNT                   1058
#define IDC_FIXMOUNT                    1059
#define IDC_PARTTION_TYPE_LIST          1059
#define IDC_PARTITION_TYPE              1060
#define IDC_PARTITION_NAME              1062
#define IDC_DEAD_LETTER_LIST            1063
#define IDC_AUTO_REMOVAL                1064
#define IDC_AUTOREMOVALTEXT             1065
#define IDC_REMOVAL_CURRENT             1066
#define IDC_DRIVER                      1067
#define IDC_SDEV_QUICK_MOUNT            1068
#define IDC_EDIT_UID                    1070
#define IDC_EDIT_GID                    1071
#define IDC_EDIT_EUID                   1072
#define ID_ABOUT                        32771
#define ID_NEW                          32772
#define ID_CHANGE                       32773
#define ID_REFRESH                      32774
#define ID_EXIT                         32775
#define ID_SERVICE                      32776
#define ID_FORMAT                       32777
#define ID_PROPERTY                     32778
#define ID_COPY                         32779
#define ID_SHOW_MAIN                    32780
#define ID_DRV_LETTER                   32781
#define ID_DONATE                       32782
#define ID_ADD_MOUNTPOINT               32783
#define ID_CHANGE_MOUNTPOINT            32784
#define ID_REMOVE_MOUNTPOINT            32785
#define ID_INSTALL_SERVICE              32786
#define ID_REMOVE_SERVICE               32787
#define ID_ENABLE_AUTOSTART             32788
#define ID_DISABLE_AUTOSTART            32789
#define ID_PERFSTAT                     32790
#define ID_PERFSTOP                     32791
#define ID_COPYALL                      32792
#define ID_QUERYPERF                    32793
#define ID_FLUSH_BUFFER                 32794
#define ID_CHANGE_PARTTYPE              32795
#define ID_REMOVE_DEAD_LETTER           32796
#define ID_DRV_QUICK_MOUNT              32797
#define ID_DRV_QUICK_REMOVE             32798
#define IDS_LISTITEM_FILESYSTEM         57671
#define IDS_LISTITEM_VOLUME             57672
#define IDS_LISTITEM_TYPE               57673
#define IDS_LISTITEM_TOTALSIZE          57674
#define IDS_LISTITEM_USEDSIZE           57675
#define IDS_LISTITEM_CODEPAGE           57676
#define IDS_LISTITEM_DEVOBJ             57677
#define IDS_LISTITEM_PARTID             57678
#define IDS_DISK_TYPE_BASIC             57679
#define IDS_DISK_TYPE_DYN               57680
#define IDS_DONATE_DECLARE              57681
#define IDS_SHOW_PROPERTY               57682
#define IDS_COPY_ITEM_TO_CLIP           57683
#define IDS_CHANGE_DRVLETTER            57684
#define IDS_EXT2_MANAGEMENT             57685
#define IDS_FLUSH_BUFFER                57686
#define IDS_CHANGE_PARTID               57687
#define IDS_RELOAD_REFRESH              57688
#define IDS_PERFMEM_STAT                57689
#define IDS_SERVICE_MANAGE              57690
#define IDS_REMOVE_DEAD_LETTER          57691
#define IDS_PERFSTAT_NAME               57692
#define IDS_PERFSTAT_UNIT               57693
#define IDS_PERFSTAT_CURRENT            57694
#define IDS_PERFSTAT_SIZE               57695
#define IDS_PERFSTAT_TOTAL              57696
#define IDS_PERFSTAT_PROCESSING         57697
#define IDS_PERSTAT_PROCESSED           57698
#define IDS_PERFSTAT_PROCESSED          57698
#define IDS_DRV_QUICK_MOUNT             57699

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        192
#define _APS_NEXT_COMMAND_VALUE         32799
#define _APS_NEXT_CONTROL_VALUE         1071
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
